import { z } from 'zod';
import { agentRequest, agentToolResult } from './agent-client.js';
const uuid = () => z.string().uuid();
const source = { entityType: z.enum(['tasks', 'projects', 'content_items']), entityId: uuid(), scope: z.enum(['personal', 'company']) };
const assistance = { commandId: uuid(), ...source, expectedSourceUpdatedAt: z.string().max(60), operation: z.enum(['draft', 'rewrite', 'critique', 'analyze']), instruction: z.string().max(4000).optional() };
function register(server, name, description, inputSchema, handler, write = false) {
  server.registerTool(name, { description, inputSchema, annotations: { readOnlyHint: !write, destructiveHint: false, idempotentHint: true, openWorldHint: name === 'request_ai_assist' } }, async args => agentToolResult(await handler(args || {})));
}
const params = input => new URLSearchParams(Object.entries(input).filter(([, value]) => value !== undefined)).toString();
function command(args, action) { const { commandId, ...input } = args; return agentRequest('/ai-assistance', { method: 'POST', body: { commandId, action, input }, timeoutMs: 90000 }); }
export function registerAssistanceTools(server) {
  register(server, 'get_work_context', 'Read exact scoped saved source, revision and recent AI candidates. Missing/partial is not an empty successful source. Content context is saved source idea, not unsaved Studio edits.', source, args => agentRequest(`/ai-assistance?${params(args)}`));
  register(server, 'get_ai_candidate', 'Read full saved candidate output in bounded sections. Start offset 0; follow nextOffset with returned outputHash until null. Source and proposal remain distinct from applied work.', { candidateId: uuid(), offset: z.number().int().min(0).max(24000).optional(), outputHash: z.string().max(64).optional() }, args => agentRequest(`/ai-assistance?${params(args)}`));
  register(server, 'get_goals', 'Read scoped objective pages; then pass objectiveId for paged metric details and latest measurements. Follow nextCursor with unchanged filters. Full observation history stays in Hub; evidence may be explicitly truncated. A linked task alone does not prove a result.', { limit: z.number().int().min(1).max(20).optional(), cursor: z.string().max(4096).optional(), scope: z.enum(['personal', 'company']), objectiveId: uuid().optional(), entityType: z.string().max(40).optional(), entityId: uuid().optional() }, args => agentRequest(`/goals?${params(args)}`));
  register(server, 'record_goal_command', 'Execute a validated goal command with stable commandId. Requires goals:write. Generate the ID once; after uncertainty check get_goal_receipt. Automatic observations are measured by the server.', { commandId: uuid(), action: z.enum(['create_objective', 'update_objective', 'create_metric', 'archive_metric', 'record_observation', 'link_entity', 'unlink_entity']), expectedRevision: z.number().int().min(1).optional(), input: z.record(z.string(), z.unknown()) }, args => agentRequest('/goals/commands', { method: 'POST', body: args }), true);
  register(server, 'get_goal_receipt', 'Recover a persisted goal command before considering a retry.', { commandId: uuid() }, args => agentRequest(`/goals/commands?${params(args)}`));
  register(server, 'save_ai_candidate', 'Save a candidate produced by this client against exact saved source revision. Requires ai:write. No model API call, no application, publication or completion. Provider attribution is client-reported; usage stays unknown.', { ...assistance, output: z.string().min(1).max(24000), client: z.string().min(1).max(80), model: z.string().max(100).nullable().optional() }, args => command(args, 'save_candidate'), true);
  register(server, 'request_ai_assist', 'Request one Gemini API generation from saved source. Requires ai:write and configured Gemini billing. Reuse commandId; never automatically retry a paid call. After timeout use get_assistance_receipt. Generated text is a candidate only.', assistance, args => command(args, 'generate'), true);
  register(server, 'record_assist_outcome', 'Record actual candidate review and minutes, separately from application or business results. Unknown baseline/review/actual minutes must stay null. Requires current candidate revision and ai:write.', { commandId: uuid(), candidateId: uuid(), expectedRevision: z.number().int().min(1), outcome: z.enum(['accepted', 'edited', 'rejected']), baselineMinutes: z.number().min(0).max(10080).nullable().optional(), reviewMinutes: z.number().min(0).max(10080).nullable().optional(), actualMinutes: z.number().min(0).max(10080).nullable().optional(), note: z.string().max(2000).optional() }, args => command(args, 'review_candidate'), true);
  register(server, 'recover_ai_candidate', 'Save an already generated result using its signed recoveryToken. No new model call. Reuse the original commandId; only the server can authenticate Gemini provenance.', { commandId: uuid(), recoveryToken: z.string().min(1).max(60000) }, args => command(args, 'recover_candidate'), true);
  register(server, 'get_assistance_receipt', 'Check the same assistance request after an unknown response. Running/unknown never authorizes a second paid generation.', { commandId: uuid() }, args => agentRequest(`/ai-assistance?${params(args)}`));
}
