import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';
import * as guidance from './index.ts';
import { GURU_CARDS, LEGEND_CARDS } from './index.ts';
import { SOURCE_PEOPLE } from './source-people.generated.js';
import {
  SOURCE_DOCUMENTS,
  SOURCE_ENTRIES,
  findSourceHeading,
  getLegendSources,
  getPersonSource,
  getSourceDocument,
  getSourceEntry,
  legendIdFromCardId,
  listSourceEntries,
  listSourcePeople,
  resolveCardSource,
} from './source-library.js';
import { LEGEND_MICRO_CARDS } from '../../apps/engine/lib/legend-cards.ts';
import {
  LIBRARY_OUTPUT,
  PEOPLE_OUTPUT,
  QUALITY_REVIEW_PATH,
  SOURCE_CONFIG,
  buildSourceLibrary,
  main,
  normalizeSourceText,
  renderOutputs,
  sourcePeopleRoster,
  splitSourceLines,
} from '../../scripts/build-guidance-source-library.mjs';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const readNormalized = path => normalizeSourceText(readFileSync(resolve(repoRoot, path), 'utf8'));
const sha256 = text => createHash('sha256').update(text, 'utf8').digest('hex');

// A card person who has no chapter of their own: the card's section lives in another entry.
const HOSTED_PEOPLE = {
  'dick-dunkel': {
    entryId: 'sales.aaron-ross',
    reason: 'MEDDIC 창안자. 플레이북에 독립 장이 없고, Aaron Ross 장의 "기법 4: Qualification — MEDDIC 프레임워크" 절이 카드의 출처다.',
  },
};

// Cards whose source.section has no heading of the same wording, reviewed one by one.
const SECTION_EXCEPTIONS = {
  'content-multiplication': {
    heading: '08. Justin Welsh — "콘텐츠는 영감이 아니라 운영체제다"',
    reason: '카드 section "콘텐츠 운영체제"는 장 제목의 명제 "콘텐츠는 영감이 아니라 운영체제다"를 줄인 말이다. 같은 말의 소제목이 없어 장 첫머리(제목)로 연결한다.',
  },
};

test('committed generated modules equal a fresh generation from the original documents', () => {
  for (const [path, content] of renderOutputs(buildSourceLibrary({ root: repoRoot }))) {
    const committed = readNormalized(path);
    assert.ok(committed === content, `${path} is stale — run npm run guidance:sources`);
    assert.match(committed, /^\/\/ GENERATED by scripts\/build-guidance-source-library\.mjs — do not edit\./);
  }
  assert.deepEqual([LIBRARY_OUTPUT, PEOPLE_OUTPUT], [
    'packages/guru-guidance/source-library.generated.js',
    'packages/guru-guidance/source-people.generated.js',
  ]);
});

test('generation is byte-identical for CRLF and LF checkouts, and --check fails only when stale', () => {
  const inputs = [QUALITY_REVIEW_PATH, ...SOURCE_CONFIG.map(doc => doc.path)];
  const makeRoot = eol => {
    const root = mkdtempSync(join(tmpdir(), `guidance-sources-${eol === '\r\n' ? 'crlf' : 'lf'}-`));
    for (const path of [...inputs, LIBRARY_OUTPUT, PEOPLE_OUTPUT]) {
      mkdirSync(dirname(join(root, path)), { recursive: true });
      writeFileSync(join(root, path), readNormalized(path).replace(/\n/g, eol));
    }
    return root;
  };
  const crlf = makeRoot('\r\n');
  const lf = makeRoot('\n');
  const log = console.log;
  const error = console.error;
  console.log = () => {};
  console.error = () => {};
  try {
    assert.deepEqual(renderOutputs(buildSourceLibrary({ root: crlf })), renderOutputs(buildSourceLibrary({ root: lf })));
    assert.equal(main(['--check'], { root: crlf }), 0, 'a CRLF working copy of the generated file still counts as current');
    writeFileSync(join(lf, LIBRARY_OUTPUT), readNormalized(LIBRARY_OUTPUT).replace('"sales.zig-ziglar"', '"sales.edited"'));
    assert.equal(main(['--check'], { root: lf }), 1, 'an edited generated file is reported stale');
    assert.equal(main([], { root: lf }), 0);
    assert.equal(main(['--check'], { root: lf }), 0);
    assert.ok(!readFileSync(join(lf, LIBRARY_OUTPUT), 'utf8').includes('\r'), 'written with LF on every OS');
    writeFileSync(join(lf, SOURCE_CONFIG[1].path), readNormalized(SOURCE_CONFIG[1].path).replace('# 2. 데이비드 오길비 (David Ogilvy)', '# 2. 오길비'));
    assert.throws(() => buildSourceLibrary({ root: lf }), /boundary heading "# 2\. 데이비드 오길비 \(David Ogilvy\)" matched 0 lines/);
  } finally {
    console.log = log;
    console.error = error;
    rmSync(crlf, { recursive: true, force: true });
    rmSync(lf, { recursive: true, force: true });
  }
});

test('every line of every document belongs to exactly one entry, reproducing it byte for byte', () => {
  assert.deepEqual(SOURCE_DOCUMENTS.map(doc => doc.path), [
    'docs/sales-guru-knowledge-base.md',
    'docs/marketing-branding-gurus.md',
    'docs/content-storytelling-people-v2.md',
    'docs/superpowers/specs/2026-09-12-legend-values-persona-cards.md',
    'docs/superpowers/specs/2026-09-21-council-mentor-guru-legend-operating-framework.md',
  ]);
  for (const doc of SOURCE_DOCUMENTS) {
    const text = readNormalized(doc.path);
    assert.ok(!text.includes('\r'), `${doc.path} is LF-normalized`);
    const lines = splitSourceLines(text);
    assert.equal(doc.sha256, sha256(text), doc.path);
    assert.equal(doc.lineCount, lines.length, doc.path);
    assert.equal(doc.charCount, [...text].length, doc.path);
    assert.equal(`# ${doc.title}\n`, lines[0], `${doc.path} title is its own H1`);
    const entries = listSourceEntries({ collection: doc.collection });
    assert.ok(entries.length > 1, doc.path);
    assert.equal(entries[0].startLine, 1);
    assert.equal(entries[entries.length - 1].endLine, lines.length);
    entries.forEach((entry, index) => {
      if (index) assert.equal(entry.startLine, entries[index - 1].endLine + 1, `${entry.id} follows the previous entry without a gap or overlap`);
      assert.ok(entry.startLine <= entry.endLine, entry.id);
      assert.equal(entry.docPath, doc.path);
      assert.equal(entry.markdown, lines.slice(entry.startLine - 1, entry.endLine).join(''), `${entry.id} is a verbatim slice`);
      assert.equal(entry.charCount, [...entry.markdown].length, entry.id);
    });
    assert.equal(entries.map(entry => entry.markdown).join(''), text, `${doc.path} concatenates back exactly`);
  }
  assert.equal(SOURCE_ENTRIES.length, SOURCE_DOCUMENTS.reduce((sum, doc) => sum + listSourceEntries({ collection: doc.collection }).length, 0));
});

test('entries carry only verbatim text plus positional metadata', () => {
  const allowed = new Set(['id', 'collection', 'kind', 'personId', 'legendId', 'name', 'title', 'docPath', 'startLine', 'endLine', 'charCount', 'headings', 'markdown']);
  for (const entry of SOURCE_ENTRIES) {
    assert.deepEqual(Object.keys(entry).filter(key => !allowed.has(key)), [], entry.id);
    assert.ok(['person', 'synthesis', 'preface'].includes(entry.kind), entry.id);
    assert.match(entry.id, new RegExp(`^${entry.collection}\\.[a-z0-9]+(?:-[a-z0-9]+)*$`));
    const firstLine = entry.markdown.split('\n')[0];
    assert.match(firstLine, /^#{1,6} /, `${entry.id} starts at a heading boundary`);
    assert.equal(firstLine.replace(/^#{1,6} /, ''), entry.title, `${entry.id} title is the heading text, unedited`);
    assert.equal(entry.headings[0].line, entry.startLine, entry.id);
    const lines = entry.markdown.split('\n');
    for (const heading of entry.headings) {
      assert.ok(heading.line >= entry.startLine && heading.line <= entry.endLine, `${entry.id}@${heading.line}`);
      assert.equal(lines[heading.line - entry.startLine], `${'#'.repeat(heading.level)} ${heading.text}`, `${entry.id}@${heading.line}`);
    }
    if (entry.kind === 'person') assert.ok(entry.name && (entry.personId || entry.legendId), entry.id);
    else assert.equal(entry.name, null, entry.id);
  }
  assert.deepEqual(new Set(SOURCE_ENTRIES.filter(entry => entry.kind === 'preface').map(entry => entry.collection)),
    new Set(SOURCE_DOCUMENTS.map(doc => doc.collection)));
});

test('headings inside fenced code are not treated as section boundaries', () => {
  const council = getSourceEntry('legend-framework.council');
  assert.ok(council.markdown.includes('### 1. 관점별 진단 (각 1~2문장)'));
  assert.ok(!council.headings.some(heading => heading.text.startsWith('1. 관점별 진단')));
});

test('every Guru card person resolves to an original entry', () => {
  const personIds = [...new Set(GURU_CARDS.map(card => card.personId))];
  for (const personId of personIds) {
    const own = getPersonSource(personId);
    const hosted = HOSTED_PEOPLE[personId];
    assert.ok(Boolean(own) !== Boolean(hosted), `${personId}: needs its own entry or a reviewed HOSTED_PEOPLE row`);
    for (const card of GURU_CARDS.filter(item => item.personId === personId)) {
      const resolved = resolveCardSource(card);
      assert.ok(resolved?.entry, card.id);
      assert.equal(resolved.entry.id, own ? own.id : hosted.entryId, card.id);
      assert.equal(resolved.hosted, Boolean(hosted), card.id);
      assert.equal(resolved.entries.length, 1, card.id);
    }
  }
  assert.ok(Object.keys(HOSTED_PEOPLE).every(personId => personIds.includes(personId)), 'no stale hosted rows');
  // The card person ids come from GURU_CARDS; the originals reuse them verbatim.
  for (const personId of ['zig-ziglar', 'dale-carnegie', 'neil-rackham', 'chris-voss', 'aaron-ross', 'keenan',
    'seth-godin', 'david-ogilvy', 'donald-miller', 'kane-kallaway', 'harry-dry', 'justin-welsh', 'dan-koe']) {
    assert.equal(getPersonSource(personId)?.personId, personId, personId);
  }
});

test('every Guru card section resolves to a heading or a reviewed exception', () => {
  for (const card of GURU_CARDS) {
    const resolved = resolveCardSource(card);
    const exception = SECTION_EXCEPTIONS[card.id];
    assert.ok(resolved.heading, `${card.id}: "${card.source.section}" found no heading`);
    if (exception) {
      assert.ok(exception.reason.length > 20, card.id);
      assert.equal(resolved.approximate, true, `${card.id} no longer needs its exception`);
      assert.equal(resolved.heading.text, exception.heading, card.id);
    } else {
      assert.equal(resolved.approximate, false, `${card.id}: "${card.source.section}" matched only approximately — review it`);
      assert.ok(['exact', 'contains', 'segment'].includes(resolved.method), card.id);
    }
  }
  assert.ok(Object.keys(SECTION_EXCEPTIONS).every(id => GURU_CARDS.some(card => card.id === id)), 'no stale exceptions');
  const meddic = resolveCardSource(GURU_CARDS.find(card => card.id === 'sales-meddic'));
  assert.equal(meddic.heading.text, '기법 4: **Qualification — MEDDIC 프레임워크**');
  const plan = resolveCardSource(GURU_CARDS.find(card => card.id === 'marketing-clear-plan'));
  assert.equal(plan.heading.text, '4단계: 계획 — 불확실성을 제거하라');
});

test('Legend cards and all sixteen Legend ids resolve by id, never by source path', () => {
  const ids = Object.keys(LEGEND_MICRO_CARDS);
  assert.equal(ids.length, 16);
  const legendEntries = SOURCE_ENTRIES.filter(entry => entry.legendId);
  assert.deepEqual(new Set(legendEntries.map(entry => entry.legendId)), new Set(ids));
  for (const id of ids) {
    const entries = getLegendSources(id);
    assert.ok(entries.some(entry => entry.collection === 'legend-framework'), `${id} has its 2026-09-21 micro-card`);
    assert.ok(entries.every(entry => entry.name === LEGEND_MICRO_CARDS[id].name), id);
    assert.deepEqual(entries.map(entry => entry.collection), [...entries.map(entry => entry.collection)].sort().reverse(), `${id}: long card first`);
  }
  assert.equal(listSourceEntries({ collection: 'legend-values', kind: 'person' }).length, 9);
  for (const card of LEGEND_CARDS) {
    const moved = { ...card, source: { ...card.source, path: 'somewhere/else.ts', section: 'unrelated' } };
    for (const candidate of [card, moved]) {
      const resolved = resolveCardSource(candidate);
      assert.equal(resolved?.kind, 'legend', card.id);
      assert.equal(resolved.legendId, legendIdFromCardId(card.id));
      assert.deepEqual(resolved.entries, getLegendSources(card.id));
    }
  }
  assert.deepEqual(getLegendSources('legend-buffett').map(entry => entry.id), ['legend-values.buffett', 'legend-framework.buffett']);
  assert.deepEqual(getLegendSources('feynman').map(entry => entry.id), ['legend-framework.feynman']);
  assert.deepEqual(getLegendSources('unknown'), []);
});

test('Legend library origin references point at these exact entries', { skip: !guidance.LEGEND_LIBRARY && 'LEGEND_LIBRARY not exported' }, () => {
  for (const legend of guidance.LEGEND_LIBRARY) {
    const entries = getLegendSources(legend.id);
    for (const ref of legend.originRefs) {
      assert.ok(entries.some(entry => entry.docPath === ref.path && entry.title === ref.heading), `${legend.id}: ${ref.heading}`);
    }
    assert.equal(entries.length, legend.originRefs.length, legend.id);
  }
});

test('listing and lookup helpers expose people without cards and never hide an entry', () => {
  assert.equal(listSourceEntries().length, SOURCE_ENTRIES.length);
  assert.ok(listSourceEntries({ kind: 'synthesis', collection: 'sales' }).some(entry => entry.title === '🏆 레전드 9인 완전 통합 시스템'));
  assert.deepEqual(listSourceEntries({ personId: 'keenan' }).map(entry => entry.id), ['sales.keenan']);
  const content = listSourcePeople({ collection: 'content' });
  assert.equal(content.length, 10);
  const withCards = new Set(GURU_CARDS.map(card => card.personId));
  assert.deepEqual(content.filter(person => !withCards.has(person.id)).map(person => person.id),
    ['alex-hormozi', 'mrbeast', 'paddy-galloway', 'brendan-kane', 'nathan-baugh', 'colin-samir-jay-clouse']);
  assert.equal(listSourcePeople({ collection: 'sales' }).length, 12);
  assert.equal(listSourcePeople({ collection: 'legend-framework' }).length, 16);
  assert.deepEqual(SOURCE_PEOPLE, sourcePeopleRoster({ entries: SOURCE_ENTRIES }));
  assert.ok(SOURCE_PEOPLE.every(person => !('markdown' in person)), 'the static roster carries no original text');
  assert.equal(getSourceDocument('sales'), getSourceDocument('docs/sales-guru-knowledge-base.md'));
  assert.equal(getSourceEntry('missing'), null);
  assert.equal(getPersonSource('dick-dunkel'), null);
  assert.equal(findSourceHeading([getSourceEntry('sales.chris-voss')], 'Calibrated Questions').heading.text, '핵심 프레임워크 3: **Calibrated Questions**');
  assert.equal(resolveCardSource(null), null);
  assert.equal(resolveCardSource({ id: 'x', kind: 'guru', personId: 'nobody', source: { path: 'docs/sales-guru-knowledge-base.md', section: 'no such section anywhere' } }), null);
});

test('verification notes follow the source-quality review and never claim a full check', () => {
  const review = readNormalized(QUALITY_REVIEW_PATH);
  for (const doc of SOURCE_DOCUMENTS) {
    const { verification } = doc;
    assert.equal(verification.basis, QUALITY_REVIEW_PATH);
    assert.equal(verification.basisSha256, sha256(review));
    // The screen shows the review's own title, not its repository path (09-25 reading-article decision).
    assert.equal(verification.basisTitle, /^# (.+)$/m.exec(review)[1].trim());
    assert.ok(verification.unverified.length > 10, doc.path);
    const reviewed = review.includes(`\`${doc.path}\``);
    assert.equal(verification.status, reviewed ? 'partial' : 'not-reviewed', doc.path);
    assert.equal(verification.checked.length > 0, reviewed, doc.path);
    assert.doesNotMatch(`${verification.checked.join(' ')} ${verification.unverified}`, /전체를 검증|모두 확인|검증 완료/, doc.path);
  }
});
