import test from 'node:test';
import assert from 'node:assert/strict';
import {register} from 'node:module';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {createOfficeCommanderState,applyOfficeCommanderAction} from '@com-moon/agent-contracts/office-commander';
import {CheckboxRow} from './hub-primitives.jsx';
register('data:text/javascript,'+encodeURIComponent(`export async function resolve(s,c,next){if(s.endsWith('.module.css'))return {url:'data:text/javascript,export default new Proxy({}, {get:(_,k)=>String(k)})',shortCircuit:true};if(s==='next/image'){const r=await next('next/image.js',c);return {url:'data:text/javascript,'+encodeURIComponent('import Image from '+JSON.stringify(r.url)+';export default Image.default||Image;'),shortCircuit:true};}return next(s,c);}`),import.meta.url);
const {OfficeCommander,OfficeCommanderTask}=await import('./office-commander.jsx');
const identity={workspaceId:'test-workspace',actorId:'test-operator'},initial=()=>createOfficeCommanderState({requestId:'render-request',scope:'classin',goal:'목적 확인',source:'고객 답장'},identity);
const render=(c,p)=>renderToStaticMarkup(React.createElement(c,p));
const visit=(node,predicate)=>{if(!node||typeof node!=='object')return null;if(predicate(node))return node;for(const child of React.Children.toArray(node.props?.children)){const result=visit(child,predicate);if(result)return result;}return null;};
function result(){const s=initial();return applyOfficeCommanderAction(s,{operationId:'result',expectedRevision:1,type:'record_result',taskId:s.tasks[0].id,payload:{body:'<script>원문 보존</script>',evidence:['원문 참조'],uncertainties:['자료 미확인']}},identity).state;}
test('real root SSR shows one title, scope requirement, zero calls and no synthetic business rows',()=>{const html=render(OfficeCommander,{scope:'all'});assert.equal((html.match(/<h2/g)||[]).length,1);assert.match(html,/이브이 커맨더/);assert.match(html,/이번 요청의 업무 범위/);assert.match(html,/모델 호출 0/);assert.match(html,/이 화면에만 남습니다/);assert.match(html,/<button[^>]*disabled=""[^>]*>업무 분담안 만들기/);assert.doesNotMatch(html,/발송 완료|업무 완료/);});
test('real task escapes originals and requires explicit human review',()=>{const s=result(),html=render(OfficeCommanderTask,{task:s.tasks[0],tasks:s.tasks,busy:false,onAction(){},draft:{},onDraft(){}});assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<script>/);assert.match(html,/<button[^>]*disabled=""[^>]*>이 결과 검토 확인/);assert.match(html,/독립 사실 인증·업무 실행 승인이 아닙니다/);});
test('real CheckboxRow callback uses a boolean and the current review enables correctly',()=>{const s=result(),changes=[];const tree=OfficeCommanderTask({task:s.tasks[0],tasks:s.tasks,busy:false,onAction(){},draft:{},onDraft:x=>changes.push(x)});visit(tree,n=>n.type===CheckboxRow).props.onChange(true);assert.deepEqual(changes,[{reviewed:true}]);const html=render(OfficeCommanderTask,{task:s.tasks[0],tasks:s.tasks,busy:false,onAction(){},draft:{reviewed:true},onDraft(){}});assert.match(html,/<button(?![^>]*disabled)[^>]*>이 결과 검토 확인/);});
test('changing owner retains the previous original but disables inherited review',()=>{let s=result();s=applyOfficeCommanderAction(s,{operationId:'owner',expectedRevision:s.revision,type:'assign_owner',taskId:s.tasks[0].id,payload:{ownerId:'umbreon'}},identity).state;const html=render(OfficeCommanderTask,{task:s.tasks[0],tasks:s.tasks,busy:false,onAction(){},draft:{reviewed:true},onDraft(){}});assert.match(html,/원문 보존/);assert.match(html,/새 결과를 다시 기록/);assert.match(html,/<button[^>]*disabled=""[^>]*>이 결과 검토 확인/);});
