import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
import {createOfficeCommanderController} from './office-commander-client.js';
import {processOfficeCommanderShadow} from '../../lib/office/commander-service.js';
import {officeCommanderReviewBinding} from '@com-moon/agent-contracts/office-commander';
const source=fs.readFileSync(new URL('./office-commander.jsx',import.meta.url),'utf8'),ast=ts.createSourceFile('commander.jsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.JSX);
const component=ast.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='OfficeCommander'),names=['intake','action','cancel','retry','reset'];
const declarations=component.body.statements.filter(s=>ts.isVariableStatement(s)&&s.declarationList.declarations.some(d=>names.includes(d.name.getText(ast))));assert.equal(declarations.length,names.length);
const compiled=ts.transpileModule(declarations.map(n=>n.getText(ast)).join('\n')+'\nreturn {'+names.join(',')+'};',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
function harness(transport){const calls=[];let seq=0,drafts={};const identity={workspaceId:'test-workspace',actorId:'test-operator'},controller=createOfficeCommanderController({id:()=>`ui-${++seq}`,send:async r=>{calls.push(r);return transport?transport(r,identity):processOfficeCommanderShadow(r,identity);}}),input={goal:'원문 세 결과',source:'고객 답장\n콘텐츠 원고\n제품 동선'};const handlers=()=>new Function('controller','input','effectiveScope','setCopyNote','setTaskDrafts',compiled)(controller,input,'classin',()=>{},update=>{drafts=update(drafts);});return {controller,handlers,calls};}
test('actual parent handlers split three tasks, record/review originals and produce eevee report',async()=>{const h=harness();await h.handlers().intake();assert.equal(h.controller.value().snapshot.tasks.length,3);for(const t of h.controller.value().snapshot.tasks){await h.handlers().action('record_result',t.id,{body:t.title+' 결과',evidence:['제공한 원문'],uncertainties:[]});const current=h.controller.value().snapshot.tasks.find(x=>x.id===t.id);await h.handlers().action('review_result',t.id,{binding:officeCommanderReviewBinding(current),reviewedSources:true});}await h.handlers().action('compile_report');assert.equal(h.controller.value().snapshot.report.complete,true);assert.equal(h.calls.length,8);});
test('actual cancel and reset handlers never resurrect a late intake',async()=>{let done;const gate=new Promise(r=>done=r),h=harness(async(r,identity)=>{await gate;return processOfficeCommanderShadow(r,identity);});const pending=h.handlers().intake();h.handlers().cancel();done();await pending;assert.equal(h.controller.value().snapshot,null);h.handlers().reset();assert.equal(h.controller.value().pending,false);});
test('actual retry handler retains the original unknown operation payload',async()=>{let count=0;const h=harness(async(r,identity)=>++count===1?{status:'unknown',error:'연결 불명'}:processOfficeCommanderShadow(r,identity));await h.handlers().intake();await h.handlers().retry();assert.deepEqual(h.calls[0],h.calls[1]);assert.equal(h.controller.value().snapshot.tasks.length,3);});
