import test from 'node:test';
import assert from 'node:assert/strict';
import {processOfficeCommanderShadow} from './commander-service.js';
import {createOfficeCommanderHubHandler,OFFICE_COMMANDER_MAX_BODY_BYTES} from './commander-http.js';
import {applyOfficeCommanderAction,officeCommanderReviewBinding} from '@com-moon/agent-contracts/office-commander';
const identity={workspaceId:'test-workspace',actorId:'test-operator'};
const body=()=>({kind:'intake',operationId:'intake-op',intake:{requestId:'request-1',scope:'classin',goal:'다음 결과',source:'고객 답장\n콘텐츠 원고'},snapshot:null});
const req=x=>new Request('http://localhost:3100/api/hub/office/commander',{method:'POST',headers:{origin:'http://localhost:3100','content-type':'application/json'},body:JSON.stringify(x)});
test('server returns explicit session-only receipt and coalesces same semantic intake',()=>{const first=processOfficeCommanderShadow(body(),identity);assert.equal(first.status,'shadow');assert.equal(first.persistence.persisted,false);assert.equal(first.source,'client_session_snapshot_unverified');const next=processOfficeCommanderShadow({...body(),operationId:'again',intake:{...body().intake,requestId:'new-request',source:'고객 답장;콘텐츠 원고'},snapshot:first.snapshot},identity);assert.equal(next.status,'duplicate_shadow');assert.deepEqual(next.snapshot,first.snapshot);});
test('server rejects authority fields, another actor and new scope over an active plan',()=>{assert.throws(()=>processOfficeCommanderShadow({...body(),budget:100},identity));const first=processOfficeCommanderShadow(body(),identity);assert.throws(()=>processOfficeCommanderShadow({...body(),snapshot:first.snapshot},{...identity,actorId:'other'}),/다른/);assert.throws(()=>processOfficeCommanderShadow({...body(),snapshot:first.snapshot,intake:{...body().intake,scope:'personal'}},identity),/새 요청/);});
test('actual HTTP runs existing guard first and no-store shadow processing second',async()=>{let calls=0;const denied=createOfficeCommanderHubHandler({guard:()=>Response.json({status:'error'},{status:403}),process:()=>calls++});assert.equal((await denied(req(body()))).status,403);assert.equal(calls,0);const handler=createOfficeCommanderHubHandler({guard:()=>null,identity:()=>identity}),response=await handler(req(body()));assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'no-store');const result=await response.json();assert.equal(result.providerCalls,0);assert.equal(result.businessWrites,false);assert.equal(result.persistence.persisted,false);});
test('HTTP rejects oversized and malformed requests and hides unexpected details',async()=>{const handler=createOfficeCommanderHubHandler({guard:()=>null,identity:()=>identity});assert.equal((await handler(req({...body(),x:'a'.repeat(OFFICE_COMMANDER_MAX_BODY_BYTES)}))).status,413);assert.equal((await handler(new Request('http://localhost:3100/api/hub/office/commander',{method:'POST',body:'{'}))).status,400);const failed=createOfficeCommanderHubHandler({guard:()=>null,identity:()=>identity,process:()=>{throw Error('sensitive provider detail');}});const response=await failed(req(body()));assert.equal(response.status,500);assert.doesNotMatch(JSON.stringify(await response.json()),/sensitive/);});
test('action requires the same operation ID and cannot request a business effect',()=>{const first=processOfficeCommanderShadow(body(),identity);const action={operationId:'step',expectedRevision:1,type:'send_email',taskId:first.snapshot.tasks[0].id,payload:{}};assert.throws(()=>processOfficeCommanderShadow({kind:'action',operationId:'step',snapshot:first.snapshot,action},identity),/지원하지/);assert.throws(()=>processOfficeCommanderShadow({kind:'action',operationId:'other',snapshot:first.snapshot,action},identity),/작업 ID/);});
test('maximum Korean packets, bindings and report remain below the byte limit',async()=>{let s=processOfficeCommanderShadow({...body(),intake:{...body().intake,source:'고객 답장\n콘텐츠 원고\n제품 동선'}},identity).snapshot;let i=0;const apply=(type,taskId,payload)=>{s=applyOfficeCommanderAction(s,{operationId:`max-${++i}`,expectedRevision:s.revision,type,...(taskId?{taskId}:{}),payload},identity).state;};for(const t of s.tasks){apply('record_result',t.id,{body:'가'.repeat(4000),evidence:Array.from({length:5},(_,n)=>String(n)+'근'.repeat(299)),uncertainties:Array.from({length:5},(_,n)=>String(n)+'미'.repeat(299))});apply('review_result',t.id,{binding:officeCommanderReviewBinding(s.tasks.find(x=>x.id===t.id)),reviewedSources:true});}apply('compile_report',null,{});const request={kind:'action',operationId:'check',snapshot:s,action:{operationId:'check',expectedRevision:s.revision,type:'check_execution',payload:{}}};assert.ok(Buffer.byteLength(JSON.stringify(request))<OFFICE_COMMANDER_MAX_BODY_BYTES);const handler=createOfficeCommanderHubHandler({guard:()=>null,identity:()=>identity});assert.equal((await handler(req(request))).status,200);});

test('maximum specialist packets, version bindings and handoffs fit the explicit HTTP bound', async () => {
  const depth = await import('@com-moon/agent-contracts/office-role-depth');
  let s = processOfficeCommanderShadow({ ...body(), intake: { ...body().intake, goal: '목'.repeat(300), source: '고객 답장\n계약 검수\n운영 일정' } }, identity).snapshot, seq = 0;
  const act = (type, i, payload) => { s = applyOfficeCommanderAction(s, { operationId: `specialist-max-${++seq}`, expectedRevision: s.revision, type, ...(i == null ? {} : { taskId: s.tasks[i].id }), payload }, identity).state; };
  for (let i = 0; i < 3; i++) {
    if (i) act('ack_handoff', i, { fromTaskId: s.tasks[0].id, ack: { status: 'accepted', toOwnerId: s.tasks[i].ownerId, consumedResultBinding: s.tasks[0].review.binding, inputSummary: '입'.repeat(500), reason: '이'.repeat(500) } });
    const task = s.tasks[i], role = depth.getOfficeRoleDepth(task.ownerId), brief = { version: depth.OFFICE_ROLE_DEPTH_VERSION, taskId: task.id, ownerId: task.ownerId, epoch: task.epoch, scope: 'classin', goal: s.goal, inputs: Object.fromEntries(role.inputFields.map(item => [item.key, '입'.repeat(500)])), sources: Array.from({ length: 3 }, (_, j) => ({ id: `source-${j}`, label: '원'.repeat(120), scope: 'classin', excerpt: '문'.repeat(1000) })), completionCriteria: Array(3).fill('완'.repeat(250)), constraints: Array(3).fill('제'.repeat(250)) };
    act('set_role_brief', i, { brief }); const b = s.tasks[i].brief;
    act('record_specialist_result', i, { output: { version: depth.OFFICE_ROLE_DEPTH_VERSION, taskId: task.id, ownerId: task.ownerId, epoch: b.epoch, scope: b.scope, briefBinding: depth.officeRoleBriefBinding(b), status: 'draft', fields: Object.fromEntries(role.outputFields.map(item => [item.key, '산'.repeat(1000)])), claims: Array.from({ length: 4 }, () => ({ kind: 'fact', text: '사'.repeat(500), sourceIds: b.sources.map(source => source.id), quote: '문'.repeat(300), reason: '이'.repeat(400) })), uncertainties: Array(4).fill('미'.repeat(250)), questions: [], nextAction: { ownerId: task.ownerId, action: '행'.repeat(400), condition: '조'.repeat(300) } } });
    act('review_result', i, { binding: officeCommanderReviewBinding(s.tasks[i]), reviewedSources: true });
  }
  act('compile_report', null, {}); const request = { kind: 'action', operationId: 'bounded-check', snapshot: s, action: { operationId: 'bounded-check', expectedRevision: s.revision, type: 'check_execution', payload: {} } };
  assert.ok(Buffer.byteLength(JSON.stringify(request)) < OFFICE_COMMANDER_MAX_BODY_BYTES); const handler = createOfficeCommanderHubHandler({ guard: () => null, identity: () => identity }); assert.equal((await handler(req(request))).status, 200);
});
