import { prepareOfficeCommanderConnection, verifyOfficeCommanderConnections } from './connection-service.js';
import { OfficeInputError } from '@com-moon/agent-contracts/office';
import {parseOfficeCommanderIntake,parseOfficeCommanderState,createOfficeCommanderState,applyOfficeCommanderAction,officeCommanderIntakeKey} from '@com-moon/agent-contracts/office-commander';
// Session notes only: no worker/provider/persistence/effect capability is granted.
export function processOfficeCommanderShadow(input,identity){
  const fail=message=>{throw new OfficeInputError(message);};
  if(!input||Object.getPrototypeOf(input)!==Object.prototype||Object.keys(input).some(k=>!['kind','operationId','intake','snapshot','action'].includes(k)))fail('커맨더 요청 형식을 확인해 주세요.');
  if(!['intake','action'].includes(input.kind)||typeof input.operationId!=='string'||!/^[a-zA-Z0-9._:-]{1,160}$/.test(input.operationId))fail('커맨더 요청 ID를 확인해 주세요.');
  let snapshot=input.snapshot==null?null:parseOfficeCommanderState(input.snapshot);if(snapshot&&(snapshot.workspaceId!==identity.workspaceId||snapshot.actorId!==identity.actorId))fail('다른 세션·워크스페이스의 요청은 사용할 수 없습니다.');if(snapshot)verifyOfficeCommanderConnections(snapshot);let duplicate=false,gate=null;
  if(input.kind==='intake'){if(input.action!==undefined)fail('인테이크와 진행 변경은 별도 요청입니다.');const intake=parseOfficeCommanderIntake(input.intake);if(snapshot){if(snapshot.intakeKey!==officeCommanderIntakeKey(intake))fail('현재 요청을 보관하거나 새 요청으로 전환한 뒤 인테이크해 주세요.');duplicate=true;}else snapshot=createOfficeCommanderState(input.intake,identity);}
  else{if(['attach_connection','record_connection_review'].includes(input.action?.type))fail('원문 투영·모델 검토는 서버 연결 경로에서만 작성합니다.');if(input.intake!==undefined||!snapshot||input.action?.operationId!==input.operationId)fail('최신 shadow 상태와 작업 ID를 확인해 주세요.');const task=snapshot.tasks.find(t=>t.id===input.action.taskId);const action=input.action.type==='check_connection_review'?{...input.action,type:'record_connection_review',payload:{review:{...task?.connection?.review,status:'unavailable',findings:['의미 모델·비용 예약은 비활성입니다. 현재 원문과 한계를 사용자가 직접 확인해야 합니다.']}}}:input.action.type==='prepare_connection'?{...input.action,type:'attach_connection',payload:snapshot.operationIds.includes(input.operationId)?{}:prepareOfficeCommanderConnection(snapshot,input.action.taskId,input.action.payload)}:input.action;const outcome=applyOfficeCommanderAction(snapshot,action,identity);snapshot=outcome.state;duplicate=outcome.duplicate;gate=outcome.gate;}
  verifyOfficeCommanderConnections(snapshot);return {status:duplicate?'duplicate_shadow':'shadow',operationId:input.operationId,requestId:snapshot.requestId,snapshot,gate,persistence:{persisted:false},source:'client_session_snapshot_unverified',providerCalls:0,businessWrites:false};
}
