import { officeContextHash } from '../repositories/office-workflow-context.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import { createOfficeCommanderState, applyOfficeCommanderAction, officeCommanderReviewBinding, officeCommanderReviewCurrent } from '@com-moon/agent-contracts/office-commander';
import { OFFICE_ROLE_DEPTH_VERSION, getOfficeRoleDepth, officeRoleBriefBinding } from '@com-moon/agent-contracts/office-role-depth';
import { OFFICE_CONNECTION_VERSION, officeConnectionBinding, calculateOfficeNetTime, parseOfficeTimeCalculation, parseOfficeWorkBoundary } from '@com-moon/agent-contracts/office-connection';
import { OFFICE_VERSION, OFFICE_DISCUSSION_VERSION, parseOfficeRequest, parseOfficeDeliberation } from '@com-moon/agent-contracts/office';
import { OFFICE_WORKFLOW_VERSION, OFFICE_CUSTOMER_PREPARATION_VERSION, createOfficeCustomerApproval } from '@com-moon/agent-contracts/office-workflow';
import { processOfficeCommanderShadow } from './commander-service.js';
import { prepareOfficeCommanderConnection, verifyOfficeCommanderConnections } from './connection-service.js';
const identity={workspaceId:'connection-workspace',actorId:'connection-operator'};
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',C='33333333-3333-4333-8333-333333333333';
let seq=0;
const initial=(ownerId='sylveon',scope='personal',brandId=A)=>{let s=createOfficeCommanderState({requestId:'connection-plan',scope,goal:'제공한 원문에서 초안 한 건 준비',source:'전문 결과',boundary:{scope,brandId}},identity);return action(s,'assign_owner',{ownerId}).snapshot;};
const action=(snapshot,type,payload={},taskId=snapshot.tasks[0].id)=>{const operationId='connection-op-'+ ++seq;return processOfficeCommanderShadow({kind:'action',operationId,snapshot,action:{operationId,expectedRevision:snapshot.revision,type,...(taskId?{taskId}:{}),payload}},identity);};
const roleInputs=ownerId=>Object.fromEntries(getOfficeRoleDepth(ownerId).inputFields.map(x=>[x.key,'제공한 자료의 입력 · '+x.label]));
function councilSource(brandId=A) {
  const request=parseOfficeRequest({ownerId:'sylveon',mode:'council',scope:'personal',participants:['sylveon','umbreon'],message:'통합 수업 관리 포지셔닝 초안을 검토해 주세요.',deliberation:{profile:'urgent'}});
  const turns=request.participants.map(ownerId=>({ownerId,round:'position',position:'제공한 문장만 사용합니다.',evidence:[],objection:'',revisionCondition:'새 원문이 있으면 재검토',changed:false,replyTo:[],changeReason:''}));
  const result={version:OFFICE_VERSION,status:'generated',ownerId:request.ownerId,mode:'council',scope:'personal',participants:request.participants,lens:null,simulation:true,answer:'흩어진 수업 운영을 하나의 흐름으로 바라봅니다.',nextAction:'추가 행동 없음.',recommendation:'주어진 포지셔닝만 사용',evidence:[],dissent:['기능·성과 미확인'],context:{source:'provided',scope:'personal',projects:[],note:'원문만 참고'},discussion:{version:OFFICE_DISCUSSION_VERSION,settings:parseOfficeDeliberation(request.deliberation,request.participants),turns,modelCalls:3}};
  return {id:'council-source',kind:'office_council',scope:'personal',boundary:{scope:'personal',brandId},artifactId:C,artifactRevision:1,label:'합성 Office 회의 원문',source:{turn:{id:C,message:request.message,request,result,officeBoundary:{scope:'personal',brandId}}}};
}
async function customerSource() {
  const request={requestId:C,intent:'customer_reply',scope:'classin',originRef:{entityType:'lead',entityId:A},expectedContextHash:'a'.repeat(64),ownerId:'flareon',mode:'draft',participants:[],message:'자료 범위에 답장 준비',boundedHistory:[],customerPreparationVersion:OFFICE_CUSTOMER_PREPARATION_VERSION};
  const context={status:'ready',scope:'classin',originRef:request.originRef,originKey:'customer:lead:'+A,contextHash:request.expectedContextHash,asOf:'2026-10-02T00:00:00Z',facts:{customer:{id:A,entityType:'lead',name:'합성 고객',brandId:null},activities:[]},sourceRefs:[{id:'lead:'+A,type:'lead',entityId:A}],missing:[],capabilities:{generate:true,applyTask:true}};
  context.contextHash=officeContextHash(context);request.expectedContextHash=context.contextHash;
  const result={version:OFFICE_WORKFLOW_VERSION,status:'generated',requestId:C,resultRevision:1,ownerId:'flareon',mode:'draft',participants:[],scope:'classin',summary:'자료 범위 확인',artifact:{kind:'text',body:'자료를 먼저 검토하시려는 요청 확인했습니다. 안내 가능한 범위를 확인하겠습니다.'},evidence:[],uncertainties:['자료 존재 미확인'],dissent:[],nextStep:null,sourceCheck:'none',context:{contextHash:context.contextHash,asOf:context.asOf,missing:[]},generation:{policyVersion:'synthetic',promptHash:'b'.repeat(64),model:'synthetic',usage:null,elapsedMs:1},customerPreparation:{version:OFFICE_CUSTOMER_PREPARATION_VERSION,purpose:'확인된 범위의 답장 준비',materials:[],questions:[]},execution:{modelCalls:2,providerRetries:0,costStatus:'unknown'}};
  const customerApproval=await createOfficeCustomerApproval(result,{sourcesReviewed:true,questionsReviewed:true});
  const receipt={status:'generated',intent:'customer_reply',requestId:C,scope:'classin',originRef:request.originRef,ownerId:'flareon',mode:'draft',resultRevision:1,result,persistence:{persisted:true},application:null};
  return {id:'customer-source',kind:'customer_reply',scope:'classin',boundary:{scope:'classin',brandId:null},artifactId:C,artifactRevision:1,label:'합성 고객 대응',source:{state:{request,context,receipt,reviewedSources:true,reviewedQuestions:true,customerApproval}}};
}
const payload=(s,source)=>({source,inputSummary:'현재 원문만 전문 입력으로 사용',excerpt:source.kind==='office_council'?source.source.turn.result.answer:source.source.state.receipt.result.artifact.body,completionCriteria:['원문 목적과 미확인 보존'],roleInputs:roleInputs(s.tasks[0].ownerId)});
const ack=s=>action(s,'ack_connection',{binding:officeConnectionBinding(s.tasks[0].connection),decision:'accepted_for_draft',sourcesReviewed:true,findingsAcknowledged:true,reason:'현재 원문과 모델 미연결 한계를 직접 확인한 합성 수신'}).snapshot;
test('same personal scope cannot cross a selected brand and legacy unlabeled Council is rejected',()=>{const s=initial();assert.throws(()=>prepareOfficeCommanderConnection(s,s.tasks[0].id,payload(s,councilSource(B))),/브랜드/);const old=councilSource();delete old.source.turn.officeBoundary;assert.throws(()=>prepareOfficeCommanderConnection(s,s.tasks[0].id,payload(s,old)),/이전 회의/);assert.throws(()=>parseOfficeWorkBoundary({scope:'personal',brandId:A,authority:true}));});
test('Council conclusion attaches to one existing owner as inputs and never inherits approval or executes',()=>{let s=initial();s=action(s,'prepare_connection',payload(s,councilSource())).snapshot;assert.equal(s.tasks.length,1);assert.equal(s.tasks[0].ownerId,'sylveon');assert.equal(s.tasks[0].state,'needs_user');assert.equal(s.tasks[0].connection.version,OFFICE_CONNECTION_VERSION);assert.equal(s.tasks[0].connection.review.status,'unavailable');assert.equal(s.tasks[0].connection.humanReview,null);assert.equal(s.tasks[0].result,null);assert.equal(s.providerCalls,0);assert.equal(s.businessWrites,false);assert.equal(s.persistence,false);assert.throws(()=>action(s,'record_result',{body:'우회',evidence:['원문'],uncertainties:[]}));s=ack(s);assert.equal(s.tasks[0].state,'queued_shadow');});
test('Council source→receive→specialist draft→human source review→Eevee report runs end to end synthetically',()=>{let s=initial();s=action(s,'prepare_connection',payload(s,councilSource())).snapshot;s=ack(s);const t=s.tasks[0],b=t.brief;const output={version:OFFICE_ROLE_DEPTH_VERSION,taskId:t.id,ownerId:t.ownerId,epoch:t.epoch,scope:b.scope,briefBinding:officeRoleBriefBinding(b),status:'draft',fields:{draft:'원문에서 초안 한 편 준비',editorialNotes:'제공 자료 범위',publicationBoundary:'실제 게시 없음'},claims:[],uncertainties:['실모델 미실행'],questions:[],nextAction:null};s=action(s,'record_specialist_result',{output}).snapshot;s=action(s,'review_result',{binding:officeCommanderReviewBinding(s.tasks[0]),reviewedSources:true}).snapshot;assert.equal(officeCommanderReviewCurrent(s.tasks[0]),true);s=action(s,'compile_report',{},null).snapshot;assert.equal(s.report.complete,true);assert.equal(s.providerCalls,0);assert.match(s.report.body,/실제 업무 실행/);});
test('customer receipt with matching customer/context/approval projects exact draft without approving commander execution',async()=>{let s=initial('flareon','classin',null);const source=await customerSource();s=action(s,'prepare_connection',payload(s,source)).snapshot;assert.equal(s.tasks[0].result.roleOutput.fields.draft,source.source.state.receipt.result.artifact.body);assert.match(s.tasks[0].result.roleOutput.fields.customerState,/관측 단계: 미확인/);assert.equal(s.tasks[0].state,'needs_user');assert.equal(officeCommanderReviewCurrent(s.tasks[0]),false);assert.throws(()=>action(s,'review_result',{binding:officeCommanderReviewBinding(s.tasks[0]),reviewedSources:true}),/수신 확인/);s=ack(s);s=action(s,'review_result',{binding:officeCommanderReviewBinding(s.tasks[0]),reviewedSources:true}).snapshot;assert.equal(officeCommanderReviewCurrent(s.tasks[0]),true);assert.equal(s.tasks[0].connection.review.executionApproved,false);});
test('customer unpersisted/foreign origin/wrong owner/stale context/tampered approval cannot enter a task',async()=>{const s=initial('flareon','classin',null);for(const mutate of [x=>x.source.state.receipt.persistence.persisted=false,x=>x.source.state.receipt.originRef.entityId=B,x=>x.source.state.receipt.ownerId='umbreon',x=>x.source.state.context.contextHash='c'.repeat(64),x=>x.source.state.customerApproval.resultHash='d'.repeat(64),x=>x.source.state.receipt.result.artifact.body='조작한 원문']){const source=await customerSource();mutate(source);assert.throws(()=>action(s,'prepare_connection',payload(s,source)));}});
test('body or canonical original mutation is rejected server-side after attach',()=>{const good=action(initial(),'prepare_connection',payload(initial(),councilSource())).snapshot;for(const mutate of [x=>x.tasks[0].connection.body='다른 결론',x=>x.tasks[0].connection.sourceSnapshot.request.message='다른 원문']){const s=structuredClone(good);mutate(s);assert.throws(()=>verifyOfficeCommanderConnections(s),/해시/);assert.throws(()=>action(s,'compile_report',{},null),/해시/);}});
test('input criteria changes invalidate the current receive confirmation and old output binding',()=>{let s=action(initial(),'prepare_connection',payload(initial(),councilSource())).snapshot;s=ack(s);const old=s.tasks[0].connection.humanReview.binding;const brief={...s.tasks[0].brief,completionCriteria:['새 기준']};s=action(s,'set_role_brief',{brief}).snapshot;assert.equal(s.tasks[0].state,'needs_user');assert.equal(s.tasks[0].connection.humanReview,null);assert.notEqual(officeConnectionBinding(s.tasks[0].connection),old);assert.throws(()=>action(s,'ack_connection',{binding:old,decision:'accepted_for_draft',sourcesReviewed:true,findingsAcknowledged:true,reason:'옛 확인'}));});
test('cancel and source boundary changes do not retain old source approvals',()=>{for(const type of ['cancel_plan','set_goal','set_boundary','assign_owner']){let s=action(initial(),'prepare_connection',payload(initial(),councilSource())).snapshot;s=ack(s);const p=type==='set_goal'?{goal:'다른 목표'}:type==='set_boundary'?{boundary:{scope:'personal',brandId:B}}:type==='assign_owner'?{ownerId:'glaceon'}:{};s=action(s,type,p,['cancel_plan','set_goal','set_boundary'].includes(type)?null:s.tasks[0].id).snapshot;assert.equal(s.tasks[0].connection,null);assert.equal(officeCommanderReviewCurrent(s.tasks[0]),false);}});
test('typed net-time checks the declared arithmetic without certifying free text or input truth',()=>{const good=calculateOfficeNetTime({kind:'net_time',basis:'estimated',weeks:4,savedMinutesPerWeek:30,setupMinutes:90,maintenanceMinutesPerWeek:10});assert.equal(good.firstPeriodMinutes,-10);assert.equal(good.repeatedPeriodMinutes,80);assert.deepEqual(parseOfficeTimeCalculation(good),good);assert.throws(()=>parseOfficeTimeCalculation({...good,firstPeriodMinutes:80}),/산식/);assert.throws(()=>calculateOfficeNetTime({...good,kind:'profit'}));});

test('a cancelled task stays cancelled after brand selection and cannot start again',()=>{let s=initial();s=action(s,'cancel_task').snapshot;s=action(s,'set_boundary',{boundary:{scope:'personal',brandId:B}},null).snapshot;assert.equal(s.tasks[0].state,'cancelled');assert.throws(()=>action(s,'start'),/취소/);});
test('changing source brand or activity after approval cannot reuse the declared context hash',async()=>{for(const mutate of [x=>x.source.state.context.facts.customer.brandId=A,x=>x.source.state.context.facts.activities.push({body:'변경된 원문'})]){const source=await customerSource();mutate(source);if(source.source.state.context.facts.customer.brandId){source.boundary.brandId=A;}const s=initial('flareon','classin',source.boundary.brandId);assert.throws(()=>action(s,'prepare_connection',payload(s,source)),/문맥 해시/);}});
test('public clients cannot supply manufactured connection packets or model-review passes',()=>{const s=initial(),prepared=prepareOfficeCommanderConnection(s,s.tasks[0].id,payload(s,councilSource()));assert.throws(()=>action(s,'attach_connection',prepared),/서버/);assert.throws(()=>action(s,'record_connection_review',{review:prepared.packet.review}),/서버/);});

test('stored receipt after reload reuses unchanged facts at a later read time without inventing its original request',async()=>{const source=await customerSource();source.source.state.request=null;source.source.state.context.asOf='2026-10-02T10:00:00Z';const s=action(initial('flareon','classin',null),'prepare_connection',payload(initial('flareon','classin',null),source)).snapshot;assert.equal(s.tasks[0].connection.sourceSnapshot.request,null);assert.equal(s.tasks[0].connection.sourceSnapshot.requestOrigin,'stored_receipt_projection');assert.equal(s.tasks[0].connection.sourceSnapshot.context.asOf,'2026-10-02T10:00:00Z');assert.equal(s.tasks[0].connection.sourceSnapshot.result.context.asOf,'2026-10-02T00:00:00Z');assert.equal(s.tasks[0].connection.humanReview,null);});
test('retries retain the connected original and require a fresh receive acknowledgement',()=>{let s=action(initial(),'prepare_connection',payload(initial(),councilSource())).snapshot;s=ack(s);const body=s.tasks[0].connection.body;s=action(s,'fail',{reason:'合成準備失敗'}).snapshot;s=action(s,'retry').snapshot;assert.equal(s.tasks[0].connection.body,body);assert.equal(s.tasks[0].connection.humanReview,null);assert.equal(s.tasks[0].state,'needs_user');assert.throws(()=>action(s,'record_result',{body:'우회',evidence:['원문'],uncertainties:[]}));});

test('selected-brand tasks cannot record unbound manual source or grant execution/budget during prepare',()=>{
 const s=initial();const brief={version:OFFICE_ROLE_DEPTH_VERSION,taskId:s.tasks[0].id,ownerId:s.tasks[0].ownerId,epoch:s.tasks[0].epoch,scope:s.scope,goal:s.goal,inputs:roleInputs('sylveon'),sources:[{id:'unbound',label:'브랜드 모름',scope:'personal',excerpt:'다른 브랜드인지 모르는 문장'}],completionCriteria:['원문'],constraints:[]};assert.throws(()=>action(s,'set_role_brief',{brief}),/브랜드/);assert.throws(()=>action(s,'prepare_connection',{...payload(s,councilSource()),budget:1000}),/권한·예산/);
});
