import assert from 'node:assert/strict';
import { execFileSync, spawnSync, spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdtempSync, readFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';

const path=new URL('../supabase/migrations/20261001_0057_research_runs.sql',import.meta.url);
test('research runs migration is present and exposes only secure bounded RPC writes',()=>{
  assert.ok(existsSync(path),'research runs durable migration must exist');
  const source=readFileSync(path,'utf8');
  for(const name of ['research_runs','research_source_documents','research_source_preparations','research_source_cursors'])assert.match(source,new RegExp(`alter table public.${name} enable row level security`));
  for(const name of ['research_run_claim_v1','research_source_claim_v1','research_model_claim_v1','research_source_complete_v1','research_run_finish_v1'])assert.match(source,new RegExp(`revoke all on function public.${name}`));
  assert.doesNotMatch(source,/^\s*(begin;|commit;)/im);
});
const available=process.getuid?.()!==0&&['initdb','pg_ctl','psql'].every(bin=>spawnSync(bin,['--version'],{stdio:'ignore'}).status===0);
const W='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',R='33333333-3333-4333-8333-333333333333',R2='44444444-4444-4444-8444-444444444444';
const quote=value=>`'${String(value).replaceAll("'","''")}'`;
test('research PostgreSQL claims serialize and replay model results without mutating reviewed drafts',{skip:available?false:'PostgreSQL binaries and non-root user required'},async()=>{
  const dir=mkdtempSync(join(tmpdir(),'research-runs-pg-')),data=join(dir,'data'),port=String(57500+process.pid%6000),env={...process.env,LC_ALL:'C'};
  const args=['-X','-qAt','-v','ON_ERROR_STOP=1','-h',dir,'-p',port,'-U','research_test','-d','postgres'];
  const sql=input=>execFileSync('psql',args,{input,encoding:'utf8',stdio:['pipe','pipe','pipe']}).trim();let started=false;
  try{
    execFileSync('initdb',['-D',data,'-U','research_test','-A','trust','--no-locale','--encoding=UTF8'],{stdio:'pipe',env});execFileSync('pg_ctl',['-D',data,'-l',join(dir,'postgres.log'),'-o',`-F -k ${dir} -p ${port} -c listen_addresses=''`,'-w','start'],{stdio:'pipe',env});started=true;
    sql(`create role anon nologin;create role authenticated nologin;create role service_role nologin bypassrls;create table public.workspaces(id uuid primary key);create table public.brands(id uuid primary key,workspace_id uuid not null,slug text,name text,status text,meta jsonb);create table public.content_items(id uuid primary key,workspace_id uuid,brand_id uuid,title text,source_idea text,source_type text,status text,meta jsonb);create table public.content_variants(id uuid primary key,workspace_id uuid,content_id uuid,title text,body text,variant_type text,channel text,status text,meta jsonb);insert into public.workspaces values('${W}');insert into public.brands values('${B}','${W}','classmoon','Class','active','{}');`);
    sql(readFileSync(new URL('../supabase/migrations/20260930_0053_research_inbox.sql',import.meta.url),'utf8'));sql(readFileSync(path,'utf8'));
    const recovery=new URL('../supabase/migrations/20261001_0058_research_pending_recovery.sql',import.meta.url);if(existsSync(recovery))sql(readFileSync(recovery,'utf8'));
    const slots=new URL('../supabase/migrations/20261001_0059_research_draft_slots.sql',import.meta.url);if(existsSync(slots))sql(readFileSync(slots,'utf8'));
    assert.equal(sql("select has_function_privilege('anon','public.research_run_claim_v1(uuid,uuid,text,jsonb)','EXECUTE')"),'f');assert.equal(sql("select has_table_privilege('service_role','public.research_source_documents','UPDATE')"),'f');
    const command={brand:'class.moon',dbSlug:'classmoon',brandId:B,topic:'education-office',limit:3};
    const claimSql=id=>`set role service_role;select public.research_run_claim_v1('${W}','${id}','${'a'.repeat(64)}',${quote(JSON.stringify(command))}::jsonb);`;
    const concurrent=input=>new Promise((resolve,reject)=>{const child=spawn('psql',args,{stdio:['pipe','pipe','pipe']});let output='',error='';child.stdout.on('data',v=>output+=v);child.stderr.on('data',v=>error+=v);child.on('close',code=>code?reject(Error(error)):resolve(JSON.parse(output.trim())));child.stdin.end(input);});
    const claims=await Promise.all([concurrent(claimSql(R)),concurrent(claimSql(R))]);assert.equal(claims.filter(item=>item.status==='claimed').length,1);assert.equal(claims.filter(item=>item.status==='running').length,1);
    const runId=claims[0].run.id;
    assert.equal(JSON.parse(sql(claimSql(R).replace('a'.repeat(64),'b'.repeat(64)))).status,'conflict');
    const raw='L1: The education ministry published guidance for schools.\nL2: A separate eligibility check is required for private academies.';
    const source={url:'https://example.org/release',title:'Guidance',text:raw,documentHash:createHash('sha256').update(raw).digest('hex'),adapterUrl:'https://example.org',official:true};
    const invoke=(name,params)=>JSON.parse(sql(`set role service_role;select public.${name}(${params});reset role;`));
    const claimed=invoke('research_source_claim_v1',`'${W}','${runId}',${quote(JSON.stringify(source))}::jsonb`);assert.equal(claimed.status,'claimed');
    const P=claimed.preparationId;
    const models=await Promise.all([concurrent(`set role service_role;select public.research_model_claim_v1('${W}','${P}');`),concurrent(`set role service_role;select public.research_model_claim_v1('${W}','${P}');`)]);assert.equal(models.filter(item=>item.status==='claimed').length,1);
    assert.equal(invoke('research_model_claim_v1',`'99999999-9999-4999-8999-999999999999','${P}'`).status,'invalid-input');
    const brief={title:'Guidance',change:'New guidance',whyBrand:'Academy owners can check applicability',facts:['The ministry published guidance.'],factEvidence:[{text:'The ministry published guidance.',sourceId:models.find(item=>item.status==='claimed').source.id,quote:'The education ministry published guidance for schools.',locator:'L1'}],interpretation:'Check applicability',conditions:'Schools',unknown:'Academy applicability',counterevidence:'',draft:'The ministry has published new guidance. Check eligibility before applying it.',sources:[{url:source.url,title:source.title,accessLevel:'full-text',locator:'L1'}],origin:'forged',verificationLevel:'verified'};
    const complete={status:'saved',brief,model:'gemini-test',usage:{totalTokenCount:100}};
    for(const locator of ['L999','L2','L1-L999'])assert.equal(invoke('research_source_complete_v1',`'${W}','${P}',${quote(JSON.stringify({...complete,brief:{...brief,factEvidence:[{...brief.factEvidence[0],locator}]}}))}::jsonb`).reason,'invalid-source-location');
    const saved=invoke('research_source_complete_v1',`'${W}','${P}',${quote(JSON.stringify(complete))}::jsonb`);assert.equal(saved.status,'saved');assert.equal(invoke('research_model_claim_v1',`'${W}','${P}'`).status,'duplicate');
    assert.equal(sql(`select payload->>'origin'||'/'||(payload->>'verificationLevel') from public.research_brief_revisions where brief_id='${saved.briefId}'`),'research-ai/unreviewed');
    sql(`update public.research_briefs set state='promoted' where id='${saved.briefId}'`);
    const run2=JSON.parse(sql(claimSql(R2))).run.id;
    assert.equal(invoke('research_source_claim_v1',`'${W}','${run2}',${quote(JSON.stringify(source))}::jsonb`).status,'duplicate');
    const changed={...source,text:raw+'\nL3: The scope changed today.'};changed.documentHash=createHash('sha256').update(changed.text).digest('hex');
    const version=invoke('research_source_claim_v1',`'${W}','${run2}',${quote(JSON.stringify(changed))}::jsonb`);assert.equal(version.status,'claimed');assert.notEqual(version.preparationId,P);assert.equal(sql(`select latest_revision from public.research_briefs where id='${saved.briefId}'`),'1');
    sql(`update public.research_source_preparations set status='generating',model_started_at=now()-interval '10 minutes' where id='${version.preparationId}'`);assert.equal(invoke('research_model_claim_v1',`'${W}','${version.preparationId}'`).status,'unknown');
    const finished=invoke('research_run_finish_v1',`'${W}','${runId}',${quote(JSON.stringify({counts:{sourceCount:1,searchCalls:1},reason:'ok',failures:[]}))}::jsonb`);assert.equal(finished.run.counts.preparedCount,1);assert.equal(finished.run.usage.totalTokenCount,100);
    const unknown=invoke('research_run_finish_v1',`'${W}','${run2}',${quote(JSON.stringify({counts:{sourceCount:1,searchCalls:0,failedCount:1},reason:'preparation-outcome-unknown',failures:[{source:'engine',reason:'preparation-outcome-unknown'}]}))}::jsonb`);assert.equal(unknown.run.status,'unknown');
    const lateBrief={...brief,factEvidence:[{...brief.factEvidence[0],sourceId:sql(`select document_id from public.research_source_preparations where id='${version.preparationId}'`)}]};
    const late=invoke('research_source_complete_v1',`'${W}','${version.preparationId}',${quote(JSON.stringify({...complete,brief:lateBrief}))}::jsonb`);assert.equal(late.status,'saved');assert.equal(sql(`select status from public.research_runs where id='${run2}'`),'success');
    assert.equal(sql(`select payload->>'supersedesBriefId' from public.research_brief_revisions where brief_id='${late.briefId}'`),saved.briefId);
    assert.equal(sql(`select state||'/'||latest_revision from public.research_briefs where id='${saved.briefId}'`),'promoted/1');
    const run3=JSON.parse(sql(claimSql('55555555-5555-4555-8555-555555555555'))).run.id;
    const newSource={...source,text:raw+'\nL3: A separate later announcement.'};newSource.documentHash=createHash('sha256').update(newSource.text).digest('hex');
    const waiting=invoke('research_source_claim_v1',`'${W}','${run3}',${quote(JSON.stringify(newSource))}::jsonb`);assert.equal(waiting.status,'claimed');
    const run4=JSON.parse(sql(claimSql('66666666-6666-4666-8666-666666666666'))).run.id;
    const recovered=invoke('research_source_claim_v1',`'${W}','${run4}',${quote(JSON.stringify(newSource))}::jsonb`);assert.equal(recovered.preparationId,waiting.preparationId);
    assert.equal(sql(`select run_id from public.research_source_preparations where id='${waiting.preparationId}'`),run4,'never-model-claimed preparation belongs to the run that safely resumes it');
    const N='77777777-7777-4777-8777-777777777777';sql(`insert into public.brands values('${N}','${W}','22nomad','Nomad','active','{}');`);
    const nomadRun=JSON.parse(sql(`set role service_role;select public.research_run_claim_v1('${W}','88888888-8888-4888-8888-888888888888','${'c'.repeat(64)}',${quote(JSON.stringify({brand:'22nomad',dbSlug:'22nomad',brandId:N,topic:'ai-labs',limit:1}))}::jsonb);reset role;`)).run.id;
    const rejected=invoke('research_source_claim_v1',`'${W}','${nomadRun}',${quote(JSON.stringify(source))}::jsonb`);assert.equal(rejected.status,'claimed');
    invoke('research_model_claim_v1',`'${W}','${rejected.preparationId}'`);
    const diagnostic={code:'quote-not-in-cited-lines',field:'facts.quote',factIndex:0,lineStart:1,lineEnd:1,rawText:'private output must disappear'};
    const failed=invoke('research_source_complete_v1',`'${W}','${rejected.preparationId}',${quote(JSON.stringify({status:'error',reason:'invalid-model-evidence',model:'gemini-test',usage:{totalTokenCount:100},validationDiagnostic:diagnostic}))}::jsonb`);
    assert.deepEqual(failed.validationDiagnostic,{code:'quote-not-in-cited-lines',field:'facts.quote',factIndex:0,lineStart:1,lineEnd:1});assert.doesNotMatch(JSON.stringify(failed),/private output/);
    assert.equal(invoke('research_source_claim_v1',`'${W}','${nomadRun}',${quote(JSON.stringify(source))}::jsonb`).status,'error','same failed paid source is never claimed again');
    const next=invoke('research_source_claim_v1',`'${W}','${nomadRun}',${quote(JSON.stringify(changed))}::jsonb`);assert.equal(next.status,'claimed','a definitively rejected draft does not consume the completed-draft quota');
    invoke('research_model_claim_v1',`'${W}','${next.preparationId}'`);
    const reserved=invoke('research_source_claim_v1',`'${W}','${nomadRun}',${quote(JSON.stringify(newSource))}::jsonb`);assert.equal(reserved.reason,'daily-quantity-reached','generating and unknown claims continue reserving the draft slot');
  }finally{if(started)spawnSync('pg_ctl',['-D',data,'-m','immediate','stop'],{stdio:'ignore',env});rmSync(dir,{recursive:true,force:true});}
});
